config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get "challenges/show"
      post "challenges/delete"
    end
  end
  resources :challenges
  get "challenges/delete/success" => "challenges#delete_success", :as => "challenge_delete_success"
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "challenges#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
    validates :name, presence: true, length: { minimum: 10, maximum: 50, message: "must be between 10 and 50 characters" }
    validates :original_content, presence: true, length: { minimum: 10, maximun: 250, message: "must be between 20 and 250 characters" }

    def process_content
        error_parse_arr = Array.new
        process_string = "{"
        begin
            sentence_arr = self.original_content.split(";")
            if sentence_arr.size > 0

                sentence_arr.each do |this_sentence|
                    tmp_phase1 = this_sentence.split(".")
                    sentece_obj = '"'+tmp_phase1[0]+'"'
                    process_string += sentece_obj + ":{"

                    tmp_phase2 = tmp_phase1[1].split("=")
                    sentence_attr = tmp_phase2[0]
                    sentence_val = tmp_phase2[1]

                    process_string += '"'+sentence_attr+'"' + ":" + '"'+sentence_val+'"' + "},"
                end
            else
                error_parse_arr.push("Sentencia revisada. Contenido ingresado no valido.\nEvaluación: #{this_sentence}")
            end
        rescue StandardError => e
            error_parse_arr.push("Error no controlado identificado durante fragmentación de la oración.\nTexto ingresado: #{original_content}\nError capturado: #{e}")
        end

        process_string = process_string[0, process_string.length-1] + "}"

        if error_parse_arr.size > 0
            error_parse_arr
        else
            process_string
        end
    end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/api/v1/challenges_controller.rb
class Api::V1::ChallengesController < ApplicationController
  require "json"
  skip_before_action :verify_authenticity_token

  def show
    token = params[:token]
    if token.present?
      this_challenge = Challenge.find_by_token(token)
      if this_challenge.present?
        render status: 200,
        json: {
          success: true,
          data: JSON.parse(this_challenge.parsing_content.to_s)
        }
      else
        render status: 200,
        json: {
          success: false,
          message: "Can't find challenge by token #{token}"
        }
      end
    else
      render status: 200,
      json: {
        success: false,
        message: "Token no present"
      }
    end
  end

  def delete
    search_challenge = Challenge.find(params[:id])
    if search_challenge.present?

      if search_challenge.destroy
        render status: 200,
        json: {
          success: true,
          message: "Registro borrado"
        }
      else
        render status: 200,
        json: {
          success: false,
          message: "No se pudo borrar"
        }
      end
    else
      render status: 200,
        json: {
          success: false,
          message: "Registro no encontrado"
        }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :set_locale

  def default_url_options
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  require "net/http"
  require "json"

  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  # GET /challenges/1 or /challenges/1.json
  def show
    @challenge = Challenge.where(id: params[:id]).first
    if !@challenge.present?
      redirect_to challenge_delete_success_path
    end
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # POST /challenges or /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)
    @result = @challenge.process_content

    if @result.class == Array
      puts "ERRORS METHOD"
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @result, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        @challenge.parsing_content = @result
        @challenge.token = SecureRandom.base64(10)

        if @challenge.save
          puts "MODEL SAVE"
          format.html { redirect_to @challenge, notice: I18n.t("sentence.successful_save") }
        else
          puts "ERRORS VALIDATE"
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @challenge.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit(:name, :country, :original_content, :parsing_content, :token)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/challenges/_challenge.html.erb
<div id="<%= dom_id challenge %>">
  <p>
    <strong>Name:</strong>
    <%= challenge.name %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= challenge.country %>
  </p>

  <p>
    <strong>Original content:</strong>
    <%= challenge.original_content %>
  </p>

  <p>
    <strong>Parsing content:</strong>
    <%= challenge.parsing_content %>
  </p>

  <p>
    <strong>Token:</strong>
    <%= challenge.token %>
  </p>

</div>

app/views/challenges/_form.html.erb
<script>
  function copyText(idx){
    console.log("PUSH IDX: "+idx)
    const source_element = document.getElementById("src_txt_example_"+idx);

    const target = document.getElementById("challenge_original_content");
    target.value += source_element.innerText;
  }
</script>


<%= form_with(model: challenge) do |form| %>
  <% if challenge.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(challenge.errors.count, "error") %> <%= t('challenge.form.errors.form_validation') %></h2>

      <ul>
        <% challenge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @result.class == Array %>
    <div style="color: red">
      <h2><%= t('challenge.form.errors.form_description') %>:</h2>
      <ul>
        <% @result.each do |error| %>
          <li><%= error.to_s %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1><%= t('challenge.form.title') %></h1>
  <p><%= t('challenge.form.instruction_1') %></p>

  <div class="form-group">
    <%= form.label t('challenge.attr.name.input'), style: "display: block", class: "form-label" %>
    <%= form.text_field :name, maxlength: 50 , class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label t('challenge.attr.country.input'), style: "display: block", class: "form-label"  %>
    <%= form.country_select :country, class: "form-input" %>
  </div>

  <h1><%= t('words.dynamic') %></h1>
  <p><%= t('challenge.form.instruction_2') %></p>
  <p><%= t('words.structure') %>:</p>
  <p><%= t('words.object') %> . <%= t('words.attribute') %> = <%= t('words.value') %> ;</p>
  <p><%= t('challenge.form.instruction_3') %></p>
  

  <p><%= t('challenge.form.instruction_4') %></p>
  <p><%= t('challenge.form.instruction_5') %></p>


  <div>
    <%= form.label t('challenge.attr.original_content.input'), style: "display: block", class: "form-label"  %>
    <%= form.text_area :original_content, maxlength: 250, class: "form-input" %>
  </div>

  <div>
    <%= form.submit t('challenge.action.create') %>
  </div>
<% end %>

<p><%= t('sentence.describe_examples') %>:</p>
  <table>
    <tr>
      <td><%= t('sentence.example_str_1') %></td>
      <td><p id="src_txt_example_1"><%= t('sentence.example_pgr_1') %></p></td>
      <td>
        <button class="round-btn" onClick="copyText(1)">
          <%= image_tag 'copiar.png', alt: 'Copy Image', class: 'round-icon-btn' %>
        </button>
      </td>
    </tr>
    <tr>
      <td><%= t('sentence.example_str_2') %></td>
      <td><p id="src_txt_example_2"><%= t('sentence.example_pgr_2') %></p></td>
      <td>
        <button class="round-btn" onClick="copyText(2)">
          <%= image_tag 'copiar.png', alt: 'Copy Image', class: 'round-icon-btn' %>
        </button>
      </td>
    </tr>
    <tr>
      <td><%= t('sentence.example_str_3') %></td>
      <td><p id="src_txt_example_3"><%= t('sentence.example_pgr_3') %></p></td>
      <td>
        <button class="round-btn" onClick="copyText(3)">
          <%= image_tag 'copiar.png', alt: 'Copy Image', class: 'round-icon-btn' %>
        </button>
      </td>
    </tr>
    <tr>
      <td><%= t('sentence.example_str_4') %></td>
      <td><p id="src_txt_example_4"><%= t('sentence.example_pgr_4') %></p></td>
      <td>
        <button class="round-btn" onClick="copyText(4)">
          <%= image_tag 'copiar.png', alt: 'Copy Image', class: 'round-icon-btn' %>
        </button>
      </td>
    </tr>
    <tr>
      <td><%= t('sentence.example_str_5') %></td>
      <td><p id="src_txt_example_5"><%= t('sentence.example_pgr_5') %></p></td>
      <td>
        <button class="round-btn" onClick="copyText(5)">
          <%= image_tag 'copiar.png', alt: 'Copy Image', class: 'round-icon-btn' %>
        </button>
      </td>
    </tr>
  </table>

app/views/challenges/delete_success.html.erb
<h3><%= t('challenge.action.save') %></h3>
<%= link_to t('words.back'), challenges_path %>

app/views/challenges/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Challenges" %>

<h1><%= t('challenge.title') %></h1>


<%= link_to "(+) "+t('challenge.action.new'), new_challenge_path, class: 'round-btn' %>

<div class="digg_pagination">
  <%= will_paginate @challenges, :previous_label => t("will_paginate.previous_label"), :next_label => t("will_paginate.next_label"), :container => false %>
</div>

<table>
  <thead>
    <tr>
      <th><%= t('challenge.attr.name.raw') %></th>
      <th><%= t('challenge.attr.country.raw') %></th>
      <th><%= t('challenge.attr.content_summary.raw') %></th>
      <th><%= t('challenge.attr.created_at.raw') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.name %></td>
        <td><%= challenge.country %></td>
        <td><%= challenge.original_content.length %></td>
        <td><%= challenge.created_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
        <td>
          <%= link_to image_tag('eye-outline.svg', alt: 'Show', class: 'round-icon-btn'), challenge_path(challenge), class: 'round-btn'  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/challenges/new.html.erb
<% content_for :title, "New challenge" %>

<%= render "form", challenge: @challenge %>

<br>

app/views/challenges/show.html.erb
<script>
  function cancelAction(){
    document.getElementById('myModal').style.display = 'none';
  }

  function openModalAction(){
    document.getElementById('myModal').style.display = 'block';
  }
  
  function confirmAction(id, i18n){
    console.log("id: "+id);

    const postData = { id: id };
    $.ajax({
        url: '/api/v1/challenges/delete',
        type: 'POST',
        data: JSON.stringify(postData),
        contentType: 'application/json',
        success: function(response){
          if(response.success){            
            window.location.href = '/challenges/delete/success?locale='+i18n;
          }
        },
        error: function(xhr){
          console.log("ERROR: "+xhr.responseJSON);
        }
    });

    document.getElementById('myModal').style.display = 'none';
  }

</script>
<p style="color: green"><%= notice %></p>

<h3><%= t('challenge.action.show.title') %></h3>
<p><%= t('words.hello') %> <%= @challenge.name %> <%= t('challenge.action.show.content_p1') %><a href="/api/v1/challenges/show?token=<%= @challenge.token %>" target="_blank">Link</a><%= t('challenge.action.show.content_p2') %></p>

<div class='json-box'>
  <% begin %>
  <pre><%= JSON.pretty_generate(JSON.parse(@challenge.parsing_content.to_s)) %></pre>
  <% rescue %>
    <p>Opps!!! este registro esta mal diseñado</p>
  <% end %>
</div>

<div>
  <%= link_to t('words.back'), challenges_path %>
  <button onclick="openModalAction()"><%= t('words.delete') %></button>
</div>


<!-- Delete Confirmation Modal -->
<div id="myModal" class="float-modal">
  <div  class="content-float-modal">
    <p><%= t('dialog.confirm.delete_item') %></p>
    <button onclick="confirmAction(<%= @challenge.id %>, '<%= params[:locale] %>')"><%= t('words.confirm') %></button>
    <button onclick="cancelAction()"><%= t('words.cancel') %></button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Deploy Ror Demo Render" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/shared/_header.html.erb
<div class="header-translate-container">
    <%= link_to "EN", url_for(locale: 'en'), class: 'translate-btn' %>
    <%= link_to "ES", url_for(locale: 'es'), class: 'translate-btn'  %>
</div>